version: '2'

services:
  web:
    build: ./nginx/
    ports:
      - "${PORT}:80"
    links:
      - wp
    volumes:
      - ./data-nginx:/var/log/nginx
    volumes_from:
      - wp:ro
    env_file:
      - .env

  wp:
    build: ./wp/
    environment:
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_HOST=mysql
    volumes:
      - /var/www/html
    volumes:
      - ./data-wordpress:/var/www/html/wp-content
    links:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./data-mysql:/var/lib/mysql

  backup:
    image: ekiwok/backup
    links:
      - mysql
    volumes:
      - ./data-wordpress:/var/www/html/wp-content
      - ./data-backup:/var/dst
    environment:
      - DB_PASS=root
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_NAME=wordpress
      - DIRECTORIES=/var/www/html/wp-content
#      - DST=/var/dst/${BACKUP_NAME}.tar.gz